require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TodoThingsController do

  # This should return the minimal set of attributes required to create a valid
  # TodoThing. As you add validations to TodoThing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TodoThingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all todo_things as @todo_things" do
      todo_thing = TodoThing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:todo_things).should eq([todo_thing])
    end
  end

  describe "GET show" do
    it "assigns the requested todo_thing as @todo_thing" do
      todo_thing = TodoThing.create! valid_attributes
      get :show, {:id => todo_thing.to_param}, valid_session
      assigns(:todo_thing).should eq(todo_thing)
    end
  end

  describe "GET new" do
    it "assigns a new todo_thing as @todo_thing" do
      get :new, {}, valid_session
      assigns(:todo_thing).should be_a_new(TodoThing)
    end
  end

  describe "GET edit" do
    it "assigns the requested todo_thing as @todo_thing" do
      todo_thing = TodoThing.create! valid_attributes
      get :edit, {:id => todo_thing.to_param}, valid_session
      assigns(:todo_thing).should eq(todo_thing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TodoThing" do
        expect {
          post :create, {:todo_thing => valid_attributes}, valid_session
        }.to change(TodoThing, :count).by(1)
      end

      it "assigns a newly created todo_thing as @todo_thing" do
        post :create, {:todo_thing => valid_attributes}, valid_session
        assigns(:todo_thing).should be_a(TodoThing)
        assigns(:todo_thing).should be_persisted
      end

      it "redirects to the created todo_thing" do
        post :create, {:todo_thing => valid_attributes}, valid_session
        response.should redirect_to(TodoThing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved todo_thing as @todo_thing" do
        # Trigger the behavior that occurs when invalid params are submitted
        TodoThing.any_instance.stub(:save).and_return(false)
        post :create, {:todo_thing => { "title" => "invalid value" }}, valid_session
        assigns(:todo_thing).should be_a_new(TodoThing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TodoThing.any_instance.stub(:save).and_return(false)
        post :create, {:todo_thing => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested todo_thing" do
        todo_thing = TodoThing.create! valid_attributes
        # Assuming there are no other todo_things in the database, this
        # specifies that the TodoThing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TodoThing.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => todo_thing.to_param, :todo_thing => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested todo_thing as @todo_thing" do
        todo_thing = TodoThing.create! valid_attributes
        put :update, {:id => todo_thing.to_param, :todo_thing => valid_attributes}, valid_session
        assigns(:todo_thing).should eq(todo_thing)
      end

      it "redirects to the todo_thing" do
        todo_thing = TodoThing.create! valid_attributes
        put :update, {:id => todo_thing.to_param, :todo_thing => valid_attributes}, valid_session
        response.should redirect_to(todo_thing)
      end
    end

    describe "with invalid params" do
      it "assigns the todo_thing as @todo_thing" do
        todo_thing = TodoThing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TodoThing.any_instance.stub(:save).and_return(false)
        put :update, {:id => todo_thing.to_param, :todo_thing => { "title" => "invalid value" }}, valid_session
        assigns(:todo_thing).should eq(todo_thing)
      end

      it "re-renders the 'edit' template" do
        todo_thing = TodoThing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TodoThing.any_instance.stub(:save).and_return(false)
        put :update, {:id => todo_thing.to_param, :todo_thing => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested todo_thing" do
      todo_thing = TodoThing.create! valid_attributes
      expect {
        delete :destroy, {:id => todo_thing.to_param}, valid_session
      }.to change(TodoThing, :count).by(-1)
    end

    it "redirects to the todo_things list" do
      todo_thing = TodoThing.create! valid_attributes
      delete :destroy, {:id => todo_thing.to_param}, valid_session
      response.should redirect_to(todo_things_url)
    end
  end

end
